### PR TITLE
Add Reactionspam Module

### PR DESCRIPTION
**Pull request by plasticsummer**
@john-phonk @iamnalinor merge after checking everything.

Hopefully, it's all set

### CODE REVIEW

**Comment by plasticsummer** [comment]
@plasticsummer бля, кароче, последний

**Comment by john-phonk** [comment]
@plasticsummer

**Comment by iamnalinor** [comment]
merge all commands into a one and add reaction argument, e.g. `.reactspam [reaction]*`

**Comment by plasticsummer** [comment]
@iamnalinor

**Comment by iamnalinor** [comment]
@plasticsummer да сука заебал тегать мне с каждого твоего тега на мыло письмо приходит

**Comment by iamnalinor** [comment]
1. Merge all commands into a one and add reaction argument, e.g. `.reactspam [count]* [reaction]*`
2. Add floodwait check, and when it happens, stop the spam execution (`return`)
3. Avoid bare except clause, use `except RPCError` or `except Exception` instead

**Comment by plasticsummer** [comment]
@iamnalinor u can check it^^

**Comment by iamnalinor** [comment]
@plasticsummer сука, я же просил не тегать

**Comment by iamnalinor** [comment]
image

wtf
just inline reaction variable to send_reaction method: `.send_reaction(..., reaction)` without big if-elif-else trees

**Comment by ZsawZ** [comment]
@iamnalinor Ты лох гитхаббот

**Comment by plasticsummer** [comment]
^

**Comment by LORD-ME-CODE** [comment]
> ```python

from pyrogram import filters, Client, types
from utils.misc import modules_help, prefix
from utils.scripts import format_exc

emojis = {
    "👍",
    "👎",
    "❤️",
    "🔥",
    "🥰",
    "👏",
    "😁",
    "🤔",
    "🤯",
    "😱",
    "🤬",
    "😢",
    "🎉",
    "🤩",
    "🤮",
    "💩",
}


@Client.on_message(filters.command("reactspam", prefix) & filters.me)
async def reactspam(client: Client, message: types.Message):
    if len(message.command) > 1:
        try:
            count = int(message.command[1])
        except ValueError:
            count = 10
    else:
        count = 10
    if len(message.command) > 2:
        reaction = message.text.split(None, 2)[2]
    else:
        reaction = "🥰"
    if reaction not in emojis:
        reaction = "🥰"
    await message.edit(f"<b>One moment...</b>")
    async for msg in client.get_chat_history(
        message.chat.id, offset_id=message.id, limit=count
    ):
        await msg.react(reaction)
    await message.edit(f"<b>Done!</b>")


modules_help["reactionspam"] = {
    "reactspam [amount]* [emoji]*": "Spam reaction to n messages in chat"
}
```

**Pull request merged**
