### PR TITLE
alive,duckduckgo, aria2,haste(hastebin uploader) & some minor change in type plugin

### PR DESCRIPTION
**Pull request by AbhiTheModder**
Kindly review ~_-

### CODE REVIEW

**Comment by lkqas** [comment]
@AbhiTheModder Ok

**Comment by ahmedov777-ai** [comment]
@lkqas Ок

**Comment by AbhiTheModder** [comment]
some animations modules added also

**Comment by AbhiTheModder** [comment]
@john-phonk & @iamnalinor sir requires your review in [aria2p(Torrent & magnet plugin)](https://github.com/Dragon-Userbot/custom_modules/pull/40/commits/3b8b5bab94605a9237755b579d1e751d358075f1)

**Comment by lkqas** [comment]
@AbhiTheModder Ok

**Comment by AmokDEV** [comment]
._.

**Comment by lkqas** [comment]
@AmokDEV

**Comment by ahmedov777-ai** [comment]
@lkqas Ok

**Comment by ahmedov777-ai** [comment]
@ahmedov777-ai Ok

**Comment by lkqas** [comment]
@ahmedov777-ai 🆗

**Pull request merged**
